# -*- coding: utf-8 -*-
"""oop's python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XKerF_kNdT78T2psRH7I6BXyWlOYpQOB
"""

class bank:
    '''WELCOME TO MY BANK '''
    bank_name='prabhas bank'
    ifsc_code='pbb111108'
    def method1(self,withdraw_amount):
        '''click withdraw'''
        self.withdraw_amount=withdraw_amount
        print(f'your with draw ammount:{self.withdraw_amount}')
    def method2(self,total_amount):
        self.total_amount=total_amount
        print(f'your total amountis:{self.total_amount}')
    def method3(self,deposit_amount):
        self.deposit_amount=deposit_amount
        print(f'deposit amount is:{self.deposit_amount}')
    def method4(transaction):
        print('your transaction is succesfully completed ')
rebel=bank()
print(rebel.__doc__)
print(rebel.bank_name)
print(rebel.ifsc_code)
print(rebel.method1.__doc__)
rebel.method1(1000)
rebel.method2(20000)
rebel.method3(100000)
rebel.method4()
rebel.__dict__

class movie:
  '''ENTER THE THEATER'''
  theater_name='prabhas'
  location_name='sulurepet'
  def method1(self,movie_name):
    self.movie_name=movie_name
    print(f'movie_name is {self.movie_name}')
  def method2(self,cinima_name):
    self.cinima_name=cinima_name
    print(f'cinima_name is{ self.cinima_name}')
  def method3(experiance):
    print('enoy the day')
prabha=movie()
print(movie.__doc__)
print(movie.theater_name)
print(movie.location_name)
prabha.method1('adhipurush')
prabha.method2('salaar')
prabha.method3()

class Bank:
  bank_name = 'SBI'
  ifsc = 'ABC123'

  def __init__(self,name,bank_num,money):
    self.name = name
    self.bank_num = bank_num
    self.money = money

  def balance_enquiry(self):
    print('Monney in your account is {}'.format(self.money))

  def saving(self,amount):
    self.money += amount
    print('{} is added into your account {} . Total is {}'.format(amount,self.bank_num,self.money))


  def withdral(self,amount):
    self.money -= amount
    print('{} is withdral into your account {} . Total is {}'.format(amount,self.bank_num,self.money))


bank_obj = Bank('Jaya Prasad','xxxxx4444',10000)
print('welcome to {}'.format(Bank.bank_name))

user_pin=input('enetr the your 4-digit pin')
password='0506'
type_op = input('''enter 1 for balance_enquiry
enter 2 for saving
enter 3 for withdral''')
if password==user_pin:
  print('valid pin')
  if type_op == '1':
    bank_obj.balance_enquiry()
  elif type_op == '2':
    amount = int(input('entyer amount for saving'))
    bank_obj.saving(amount)
  else:
    amount = int(input('entyer amount for withdral '))
    bank_obj.withdral(amount)

a="venkatesh"
b="prabhas"
c='venkatesh'
d='prabhas'
if a==b:
  print('it is  vnkatesh')
  if a!=b:
    print('it is venkatesh')
    if b==a:
      print('it is not prabhas')
      if b==d:
        print('it is prabhas')
else:
  print('venkatesh is not venkates')

a="venkatesh"
b="prabhas"
if a==b:
  print('it is not prabhas')
else:
  print('he is prabhas')

