# -*- coding: utf-8 -*-
"""PRACTICE PROGRAMS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LEZxM8emOL7v0S3kbtLMpcZ2ttsaCd8T
"""

str='venkatesh'
print('ss'in str)

"""string is 'venkatesh' we print the statement 'ss' an operator the string is venkatesh ther is no 'ss' so it is false

# membership **operator** in
"""

str='venkatesh'
print('ss' not in str)

"""there is using  an operator notin then if we given the string elements it is false we shouldn't given in there string it is true why because if we given elements there is not in the string so it is true

# **not in**
"""

a=6
print(type(a))

"""# **type function** integer

"""

a=5.6
print(type(a))

"""# **type function float**"""

a='venkatesh'
print(type(a))

"""# **type function string**"""

list=[1,2,3,4,5,6]
print(list[0])
print(list[4])

"""# **creatin list** **integers**"""

numbers=(1,2,3,4,5,6)
print(numbers[0])

"""# **tuple**"""

set1={1,2,3,4,5,6}
set2={7,8,9,0,22,66}
union=set1.union(set2)
print(union)

"""# **set **

# arthimetic **operators**
"""

a=6
b=8
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b)
print(a**b)

"""# **Relational operators**"""

a=12
b=21
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)
print(a==b)
print(a!=b)

"""# **Assingment operators**"""

a=2
a+=a
print(a)

a=5
a-=a
print(a)

a=3
a*=a
print(a)

a=4
a/=a
print(a)

a=6
a//=a
print(a)

"""the floor(//) division is allways gives  quotiant  it gives float values but division (/)module is allwyas given integer value"""

a=7
a**=a #power
print(a)

a=9
a%=a
print(a)

x=5
y=10
print(x > 0 and y > 0)

x=5
y=10
print(x<0 or y<0)

"""returns true if at least one of the operand is true otherwise returns boath operand is fals"""

y = False
print(not y)

"""# **Identify operator**"""

x=1
y=2
print(x is y)

"""if the x , y is same object it returns to true
if the x , y isnot same object or value is return to false
"""

x="venkatesh"
y=x
print(x is y)

x="venkatesh"
y='prabhas'
print(x is not y)

a=18
if a > 19:
  print("person is elgible")
else:
  print("person is not elgible")

a=int(input())
b=int(input())
if a > b:
  print("given valuie is positive")
elif a > b:
  print("given value is negative")
else:
  print("given value is zero")