# -*- coding: utf-8 -*-
"""python practiece

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1thFnj-7dBN2q-zyznsTCKuubxYfuDIAi

# concatination
"""

list1=[10,20,30]
list2=[0,'a',5,'v','true']
list=list1+list2                # concatination " + " addition of 2 lists

"""# repetition"""

n=int(input('enter the value'))
list1=[1,2,3]
list=list1*n     #repetition ' * '
print(list)

"""# list packing"""

a=10       #int value
b='v'          # string
c=6.6               #float
d='true'              #boolean
list=[a,b,c,d]
print(list)

list=[1,2,3,4,5,6]
print(list[-1::-1])

"""# list unpacking"""

list=['venkatesh','mahendra']
 a,b=list
 print(a)
 print(b)

"""# list function()
# len()
"""

list=['venkatesh','mahendra']
length=len(list)  # length of list
print(length)

"""# count()"""

list='venkates' #given list is string
print(list.count('e'))

"""# index()"""

list=[1,2,3,4,'v','True',' ' ]
print(list.index(' ' ))
print(list.index('True'))
print(list.index(4))
print(list.index(3))
print(list.index(10))

"""# max()"""

list=[10,50,100,1000,20]
print(max(list))

"""# min()"""

list=[10,50,100,1000,20,-1]
print(min(list))

"""# sum()"""

list=[10,50,100,1000,20]
print(sum(list))

list=[10,50,100,1000,20,False,True]
print(sum(list))

"""# all()"""

list=[10,50,100,1000,20]
print(all(list))

list=[10,50,100,1000,2,True,False]
print(all(list))

list=[1,0,0.0]
print(all(list))

print(all([ True,True,True,True]))
print(any([ False,False]))