# -*- coding: utf-8 -*-
"""STRING () METHODS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CGDxKRlbEp_mOpQWzCyvscoIHEz9AgEq

# STRING METHODS
"""

str="python"
print(str)
print(str[0])   #indexing
print(str[1:4])           #slicing positive
print(str[::-1])                               #revers slicing
print(str[:-1])                                                #forword back slicing
print(str[0:3:2])        #step slicicng
print(str[0:])                             #vlue dont change why beacause its only startin g point no ending and step
print(str[:4])   #exicute only 0 to 3 positions

"""## method 1 (delet of string)"""

name="amarendra bahubali"
del(name)               #delt its name not defined this language consider the " del" only

"""# concatination of string (+)"""

name1="amarendra"
name2="bahubali"
name3=name1+" "+name2
print(name3)

name1="amarendra"
name2="bahubali"
print(name1+" "+name2) # concatination it combine the two varible

name1="amarendra"
name2="bahubali" # we miss the paranthasis () " incomplete input error "
print(name1+" "+name2

"""# **Repitition** of string"""

name="amarendra"
print(name*5,sep=" ")

"""# **captalization**"""

str="amarendra mahendra"
print(str.capitalize())

"""# **count of string**"""

str="amarendra"
print(str.count("a"))

"""# **swap in string**"""

Str="amarensdra bahubali MAHENDRA bahubali"
print(str.swapcase())

"""LOWER CASE OF STRING


"""

Str="amarensdra bahubali MAHENDRA bahubali"
print(str.lower())

Str="amarensdra bahubali MAHENDRA bahubali"
print(str.islower())

"""# upper case of strring"""

Str="amarensdra bahubali MAHENDRA bahubali"
print(str.upper())

Str="amarensdra bahubali MAHENDRA bahubali"
print(str.isupper())

"""# **title of string**"""

Str="amarensdra bahubali MAHENDRA bahubali"
print(str.title())

"""# **strip of string**"""

Str=" amarensdra bahubali MAHENDRA bahubali "
print(str.strip())

"""left strip"""

Str=" amarensdra bahubali MAHENDRA bahubali "
print(str.lstrip())

"""right strip"""

Str=" amarensdra bahubali MAHENDRA bahubali "
print(str.rstrip())

"""split of string"""

Str="amarensdra bahubali MAHENDRA bahubali"
print(str.split())  # the split method is the given out put in list type

Str="amarensdra bahubali MAHENDRA bahubali"
print(str.split("b"))

"""# **finde of string**"""

Str="amarensdra bahubali MAHENDRA bahubali" #strting position consider towards  -->right side
print(str.find("a")) #len(36)

Str=" amarensdra bahubali MAHENDRA bahubali "  # eding position to starting count the charector position           <-- left side
print(str.rfind("a"))

help(str)

str="i\tlove\tyou\tmyself"
print(str.expandtabs(5))

str="\i\tlove\tyou\tmyself"     #we miss the "   t  " that time will give the same symbole in the out put
print(str.expandtabs(5))

str= "venktaesh is hero "
print(str.index('is'))

str= "venktaesh is hero "
print(str.find('is'))

str= "venktaesh is hero "
print(str.index('m'))   # to give the inedex out of the string the give valuie error

"""# {} formate method"""

str="venkatesh"
age="22"
print("he nameis {}and {} years of old".format(str,age))

"""**# strings list**

# 1 write a program to print the lenght of string.
# 2 write a program concatinate two strings.
# 3 write a program to print to convert string uppercase.
# 4 write a program to print to convert string lowercase.
# 5 write a program strtwith a specific prefix.
# 6 write a program strtwith a specific suffix.
# 7 write a program to print the index of string.
# 8.write a program to print the count of string.
# 9.write a program to print replace of string in other charecter. **bold text**
##
"""

str="venkatesh"
print(len(str))

str1="venkatesh" str2="prabhas"
str3=str1+ " "+str2
print(str3)

str="venkaresh"
print(str.upper())

str="VENkateSH"
print(str.lower())

str="venkatesh"
 print(str.endswith("h"))

str="venkatesh"
print(str.startswith('v'))

str='venkatesh'
 print(str.index('a'))

str='prabhas'
print(str.count('a'))

str='venkatesh'
new_str=str.replace('venkatesh','mahendra')
print(new_str)

str='venkatesh'
print(str.split())      #split is the given the out put is list format

n=input("enter the string")
print(len(n))

"""given input is string will give you out put all position of string"""

n=input("enter the string")
print(len(n))

n=input("enter the string")
print(n.upper())

n=input("enter the string")
list=[]
for i in n:
  if i.isnumeric():
    print(i)

n=input('enter the string')
list=[]
for i in n:
  if i in 'aeiou':
    list.append(i)
    print(len(list))

n=input('enter the string')
list=[]
for i in n:
  if i in '12345678':
    list.append(i)
    print(len(list))

"""# palindrome or not"""

n=input("enter the input")
if n==n[::-1]:
  print('it is a palindrom')
else:
  print("it is not palindrome")

n=input("enter the input")
p=n[::-1]
print(p)

"""# revers string"""

n=input("enter the input")
print(n[::-1])

"""# all words first is capital"""

n=input("enter the input")
print(n.title())

n=input('enter the input')
if '@' in n and '.' in n: # used in " in " define the in or not
  print('given mail is valid')
else:
  print('given mail is not valid')

n=input('enter the input')
new_str=str.replace(n,'mahendra')
print(new_str)

n=input("enter the input")
upper=0
lower=0
digit=0
for i in n:
  if i.isupper():
    upper+=1
  elif i.islower():
    lower+=1
  else:
    digit+=1
if upper>=1 and lower >=3 and digit >=3:
  print("valid password")
else:
  print("password not valid")

"""# string () methods in list

1. write a python program that takes a list of number as input and prints the sum of all the numbers
"""

n1=input("enter the list")
n2=input('enter the list')
n3=n1+n2
print(n3)

"""2 . write a python program that takes a list of strings as input and print the concatination of all strings"""

list1='prabhas','raju'
list2='venkatesh','mahendra'
list3=list1+list2
print(list3)

"""3"""

n=[10,50,60]
largest_number=max(n)
print(largest_number)

"""4"""

n=[10,50,60]
smalest_number=min(n)
print(smalest_number)

n=int(input("enter the "))
sum=0
p=n
while n>0:
  a=n%10
  sum+=a
  n=n//10
if p%sum==0:
  print('harshad')
else:
  print('not harshad')

"""[10:05 AM, 7/10/2023] Jaya Prasad Sir: 1. Write a Python program that takes a list of numbers as input and prints the sum of all the numbers.
2. Write a Python program that takes a list of strings as input and prints the concatenation of all the strings.
3. Write a Python program that takes a list of numbers as input and prints the largest number in the list.
4. Write a Python program that takes a list of strings as input and prints the shortest string in the list.
5. Write a Python program that takes a list of numbers as input and prints a new list with only the even numbers.
6. Write a Python program that takes a list of strings as input and prints a new list with only the strings that have more than 5 characters.
7. Write a Python program that takes a list of numbers as input and prints a new list with the numbers squared.
8. Write a Python program that takes a list of strings as input and prints a new list with the strings reversed.
9. Write a Python program that takes a list of numbers as input and prints the average of all the numbers.
10. Write a Python program that takes a list of strings as input and prints the number of strings that start with the letter 'A'.
[10:05 AM, 7/10/2023] Jaya Prasad Sir: 1. Write a Python program that takes two lists of numbers as input and returns a new list containing the common elements between the two lists.

2. Write a Python program that takes a list of words as input and returns a new list with the words sorted in alphabetical order.

3. Write a Python program that takes a list of numbers as input and returns the product of all the numbers in the list.

4. Write a Python program that takes a list of strings as input and returns a new list with the strings sorted by their lengths (from shortest to longest).

5. Write a Python program that takes a list of numbers as input and removes all duplicates, returning a new list with unique elements only.

6. Write a Python program that takes a list of strings as input and returns a new list with the strings reversed, but maintaining the order of the original list.

7. Write a Python program that takes a list of numbers as input and returns the second largest number in the list.

8. Write a Python program that takes a list of strings as input and returns the number of times each word appears in the list as a dictionary.

9. Write a Python program that takes a list of numbers as input and returns a new list with only the prime numbers from the original list.

10. Write a Python program that takes a list of strings as input and checks if there are any anagrams present (strings that contain the same characters in a different order), returning True or False.

5 Write a Python program that takes a list of numbers as input and prints a new list with only the even numbers.
"""

n=input('enter the list')
for i in n:
  i%2==0
  print(i)